In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# **Pandas Series**

* Tek sütun olarak yazar.
* İçine farklı veri yapıları yazılabilir.

In [2]:
student = ["Elina", 20, "CE"]
print(student)
print(type(student))

['Elina', 20, 'CE']
<class 'list'>

In [3]:
student = ["Elina", 20, "CE"]
ps_student = pd.Series(student)
print(ps_student)
print(type(ps_student))

0    Elina
1       20
2       CE
dtype: object
<class 'pandas.core.series.Series'>

* **0 1 2 index tir**

In [4]:
student = {
    "name": "elina",
    "age": 20,
    "depatrment": "CE"
}
print(student)
print(type(student))
print("-----")
ps_student = pd.Series(student)
print(ps_student)
print(type(ps_student))

{'name': 'elina', 'age': 20, 'depatrment': 'CE'}
<class 'dict'>
-----
name          elina
age              20
depatrment       CE
dtype: object
<class 'pandas.core.series.Series'>

In [5]:
student = pd.Series(["elina",20,"CE"])
print(student)
print(type(student))

0    elina
1       20
2       CE
dtype: object
<class 'pandas.core.series.Series'>

In [6]:
numbers = pd.Series([24,37,43])
print(numbers)
print(type(numbers))

0    24
1    37
2    43
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
boolens = pd.Series([True,False,True])
print(boolens)
print(type(boolens))

0     True
1    False
2     True
dtype: bool
<class 'pandas.core.series.Series'>

In [8]:
student = pd.Series(["elina",20,"CE"], index = ["name","age","department"])
print(student)

name          elina
age              20
department       CE
dtype: object

# index yerindeki 0 1 2 i yerine yazı yazma

In [9]:
student = pd.Series(data = ["elina",20,"CE"], index = ["name","age","department"])
print(student)
print("-------")
print(student.values) #değişkeni yani ['elina' 20 'CE'] i yazar
print("-------")
print(student.index)# indexi yaniIndex(['name', 'age', 'department'] i yazar
print("-------")
print(student.shape)# 3,1 lik matrisi (3,)tuple olarak yazar
print("-------")
print(student.ndim)# boyutunu yazar yani 1 yazar
print("-------")
print(student.dtype)#object olarak yazar
print("-------")
print(student.size)#eleman sayısını yazar yani 3 elemanlıdır
print("-------")
print(student.age)# age i yani 20 yazar

name          elina
age              20
department       CE
dtype: object
-------
['elina' 20 'CE']
-------
Index(['name', 'age', 'department'], dtype='object')
-------
(3,)
-------
1
-------
object
-------
3
-------
20

# in

In [10]:
student = pd.Series(data = ["elina",20,"CE"], index = ["name","age","department"])
x = "name" in student
print(x)
print("--------")
y = "job" in student
print(y)

True
--------
False

In [11]:
student = pd.Series(data =["elina",20,"CE"], index = ["name","age","department"])
x = "ahmet" in student.values
print(x)
print("------")
y = "elina" in student.values
print(y)

False
------
True

In [12]:
numbers = pd.Series([4, 2.5, 2])
print(numbers)
print("------")
print(numbers.sum())# toplamını yazar
print("------")
print(numbers.mean())#ortalamasını yazar
print("------")
print(numbers.product())#eleamnalrın çarpımını yazar

0    4.0
1    2.5
2    2.0
dtype: float64
------
8.5
------
2.8333333333333335
------
20.0

# Pandasta elemanlara ulaşma ve elemanları değiştirme

In [13]:
student =pd.Series(data = ["elina","elinson",20,"CE"], index = ["name","surname","age","depatment"])
print(student)

name           elina
surname      elinson
age               20
depatment         CE
dtype: object

* data ve index yazmasakda olur.

In [14]:
student =pd.Series(["elina","elinson",20,"CE"],["name","surname","age","depatment"])
print(student)
print("-----")
print(student["name"])
print(type(student["name"]))
print("-----")
print(student[["name","age"]])# 1 den fazla değer yazıyorsak 2 tane köşeli parantez yazmamız lazım
print(type(student[["name","age"]]))

name           elina
surname      elinson
age               20
depatment         CE
dtype: object
-----
elina
<class 'str'>
-----
name    elina
age        20
dtype: object
<class 'pandas.core.series.Series'>

In [15]:
student =pd.Series(["elina","elinson",20,"CE"],["name","surname","age","depatment"])
print(student[0])

elina

/tmp/ipykernel_34/3575332412.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(student[0])

In [16]:
student =pd.Series(["elina","elinson",20,"CE"],["name","surname","age","depatment"])
print(student[[0,2]])

name    elina
age        20
dtype: object

/tmp/ipykernel_34/3538777051.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(student[[0,2]])

In [17]:
student =pd.Series(["elina","elinson",20,"CE"],["name","surname","age","depatment"])
print(student[0:3])

name         elina
surname    elinson
age             20
dtype: object

In [18]:
student =pd.Series(["elina","elinson",20,"CE"],["name","surname","age","depatment"])
print(student[-2])

20

/tmp/ipykernel_34/1512003453.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(student[-2])

# Bütün elemanları yazdırma

In [19]:
student =pd.Series(["elina","elinson",20,"CE"],["name","surname","age","depatment"])
print(student[0:])

name           elina
surname      elinson
age               20
depatment         CE
dtype: object

In [20]:
student =pd.Series(["elina","elinson",20,"CE"],["name","surname","age","depatment"])
print(student[-2:])

age          20
depatment    CE
dtype: object

In [21]:
student =pd.Series(["elina","elinson",20,"CE"],["name","surname","age","depatment"])
print(student[0:3])
print(student["name":"depatment"])# indexe göre yazarsak sondaki de dahil oluyor

name         elina
surname    elinson
age             20
dtype: object
name           elina
surname      elinson
age               20
depatment         CE
dtype: object

# loc --> location, iloc --> index location

* loc kullandığımızda parametre olarak index deki değeri yazarız.Mesela:

In [22]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
print(student.loc["name"])
print(student.loc["age"])

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------
elina
20

* iloc kullandığımızda parametre olarak index sayısı yazılır.Mesela:

In [23]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
print(student.iloc[1])
print(student.iloc[3])

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------
elinson
CE

# Elemanları değiştirme

In [24]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
student["name"] = "elif"
print(student)

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------
name             elif
surname       elinson
age                20
department         CE
dtype: object

* name i değiştirdik

# iloc kullanarak değiştirmek

In [25]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
student.iloc[2] = 15
print(student)

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------
name            elina
surname       elinson
age                15
department         CE
dtype: object

* *Pandas Series --> mutable dır. Yani Oluşturduktan sonra değiştirebiliyoruz*

# Eleman Silme

In [26]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
student.drop("name")
print(student)

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------
name            elina
surname       elinson
age                20
department         CE
dtype: object

* Böyle yaparsak orijinal veride değişiklik yapmayız.Böyle olsaydı bir veri kolay kolay silinebilirdi.Bu yüzden aşağıdaki gibi yapmak lazım.

In [27]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
student2 = student.drop("name")
print(student2)

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------
surname       elinson
age                20
department         CE
dtype: object

In [28]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
student.drop("name",inplace = True)
print(student)

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------
surname       elinson
age                20
department         CE
dtype: object

* Ama illaki o veriyi silmek istiyorsak, böyle yaparız. Yani inplace metodunu kullanırız.

# len() kullanmak ve seriesi liste ve dictinary yapmak.

In [29]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
print(len(student))
print("-------")
print(list(student))
print("-------")
print(dict(student))

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------
4
-------
['elina', 'elinson', 20, 'CE']
-------
{'name': 'elina', 'surname': 'elinson', 'age': 20, 'department': 'CE'}

# sorted()

In [30]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
print(sorted(student))

name            elina
surname       elinson
age                20
department         CE
dtype: object
-------

TypeError: '<' not supported between instances of 'int' and 'str'

* Hata verir. Çünki string ve integer ları numeric olarak sıralayamaz.

# max(), min()

In [ ]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
print(max(student))

* Burada yazmadı ama derleyicide yazarsak,en sondakini yazar yani "CE" yazar

In [ ]:
student = pd.Series(["elina","elinson",20,"CE"],["name","surname","age","department"])
print(student)
print("-------")
print(min(student))

* Burada yazmadı ama derleyicide yazarsak, ilk elemanı  yazar yani "elinson" yazar